services:
  - type: web
    name: leyvacar-ml-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FIREBASE_PROJECT_ID
        value: leyvacarsmovil
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
    scaling:
      minInstances: 0
      maxInstances: 1